name: httpd-minimal-golang-example
frameworks: ubuntu-core-15.04-dev1
vendor: Alexander Sack <asac@canonical.com>
architecture: amd64
icon: meta/go.svg
version: 1.0.1
services:
 - name: webserver
   description: "snappy example: golang mini webserver"
   start: ./golang-httpd-minimal-example
ports:
 required: 80

