name: go-example-webserver
vendor: Alexander Sack <asac@canonical.com>
architecture: [amd64, armhf]
icon: meta/go.svg
version: 1.0.3
services:
 - name: webserver
   description: "snappy example: golang mini webserver"
   start: ./magic-bin/go-example-webserver
ports:
 required: 8081

