name: go-example-webserver
vendor: Alexander Sack <asac@canonical.com>
architecture: [amd64, armhf]
icon: meta/go.png
version: 1.0.8
services:
 - name: webserver
   description: "snappy example: golang mini webserver"
   start: ./magic-bin/go-example-webserver
   caps:
    - network-client
    - network-service

