name: hello-world
version: 2.0
vendor: Snappy Developers <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
binaries:
 - name: bin/echo
   caps: []
 - name: bin/env
   caps: []
 - name: bin/evil
   caps: []
 - name: bin/showdev
   caps: []
 - name: bin/usehw
   caps: []
 - name: bin/sh
   caps: []
