name: hello-world
version: 1.0.11
vendor: Snappy Developers <snappy-devel@lists.ubuntu.com>
icon: meta/hello.svg
binaries:
 - name: bin/echo
   caps: []
 - name: bin/env
   caps: []
 - name: bin/evil
   caps: []
