name: xkcd-webserver.canonical
version: 0.3.4
vendor: Michael Vogt <michael.vogt@ubuntu.com>
icon: meta/xkcd.svg
services:
 - name: xkcd-webserver
   start: bin/xkcd-webserver
   description: A fun webserver

