name: xkcd-webserver
version: 0.6
vendor: Snappy Developers <snappy-devel@lists.ubuntu.com>
icon: meta/xkcd.png
services:
 - name: xkcd-webserver
   start: bin/xkcd-webserver
   description: A fun webserver
   caps:
    - network-client
    - network-service
