name: xkcd-webserver
version: 0.4
vendor: Snappy Developers <snappy-devel@lists.ubuntu.com>
icon: meta/xkcd.png
services:
 - name: xkcd-webserver
   start: bin/xkcd-webserver
   description: A fun webserver
   caps:
   - networking
   - network-service
