name: hello-dbus-app
version: 1.0.1
architecture: [amd64, armhf, i386]
vendor: Snappy Developers <snappy-devel@lists.ubuntu.com>
icon: meta/hello.png
frameworks:
  - hello-dbus-fwk
binaries:
  - name: client
    exec: bin/dbus_message.client
    description: "hello-dbus-fwk test client"
    caps:
      - hello-dbus-fwk_client
