name: golang-httpd-minimal
frameworks: ubuntu-core-15.04-dev1
maintainer: Alexander Sack <asac@ubuntu.com>
architecture: amd64
icon: go.svg
version: 1.0.1
services:
 - name: webserver
   description: "snappy example: golang mini webserver"
   start: ./golang-httpd-minimal
ports:
 required: 80

